services:

  gerencia:
    build:
      context: ../
      dockerfile: build/Dockerfile.gerencia
    ports:
      - "5000:5000"

  gravacao:
    build:
      context: ../
      dockerfile: build/Dockerfile.gravacao
    ports:
      - "5001:5001"
    links:
      - gerencia
