## Build
FROM golang:1.16-buster AS build

LABEL project="vigia-go"
LABEL app="gerencia-admin"

WORKDIR /app

COPY ./go.mod go.sum ./
RUN go mod download

COPY ./cmd ./cmd
COPY ./internal ./internal

RUN go build -o ./build/gerencia-admin ./cmd/gerencia-admin

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /app

COPY --from=build /app/build/gerencia-admin ./gerencia-admin

USER nonroot:nonroot

ENTRYPOINT ["/app/gerencia-admin"]