## Build
FROM golang:1.16-buster AS base

LABEL project="vigia-go"

WORKDIR /app

COPY ./go.mod go.sum ./
RUN go mod download

FROM base AS build_gerencia

LABEL app="gerencia"

COPY ./cmd ./cmd
COPY ./internal ./internal

RUN go build -o ./build/gerencia ./cmd/gerencia

FROM gcr.io/distroless/base-debian10

WORKDIR /app

COPY --from=build_gerencia /app/build/gerencia ./gerencia

USER nonroot:nonroot

ENTRYPOINT ["/app/gerencia"]