services:

  gerencia:
    build:
      context: ../
      dockerfile: deployments/dockerfile.gerencia
    env_file:
      - .env.dev
    depends_on:
      - gravacao
    links:
      - gravacao
    command: ["iniciar"]

  gravacao:
    build:
      context: ../
      dockerfile: deployments/dockerfile.gravacao
    env_file:
      - .env.dev
    command: ["iniciar"]