// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GerenciaClient is the client API for Gerencia service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GerenciaClient interface {
	RegistrarServidorGravacao(ctx context.Context, in *RegistrarServidorGravacaoReq, opts ...grpc.CallOption) (*RegistrarServidorGravacaoResp, error)
	DatabaseConfig(ctx context.Context, in *DatabaseConfigReq, opts ...grpc.CallOption) (*DatabaseConfigResp, error)
}

type gerenciaClient struct {
	cc grpc.ClientConnInterface
}

func NewGerenciaClient(cc grpc.ClientConnInterface) GerenciaClient {
	return &gerenciaClient{cc}
}

func (c *gerenciaClient) RegistrarServidorGravacao(ctx context.Context, in *RegistrarServidorGravacaoReq, opts ...grpc.CallOption) (*RegistrarServidorGravacaoResp, error) {
	out := new(RegistrarServidorGravacaoResp)
	err := c.cc.Invoke(ctx, "/gerencia.Gerencia/RegistrarServidorGravacao", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gerenciaClient) DatabaseConfig(ctx context.Context, in *DatabaseConfigReq, opts ...grpc.CallOption) (*DatabaseConfigResp, error) {
	out := new(DatabaseConfigResp)
	err := c.cc.Invoke(ctx, "/gerencia.Gerencia/DatabaseConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GerenciaServer is the server API for Gerencia service.
// All implementations must embed UnimplementedGerenciaServer
// for forward compatibility
type GerenciaServer interface {
	RegistrarServidorGravacao(context.Context, *RegistrarServidorGravacaoReq) (*RegistrarServidorGravacaoResp, error)
	DatabaseConfig(context.Context, *DatabaseConfigReq) (*DatabaseConfigResp, error)
	mustEmbedUnimplementedGerenciaServer()
}

// UnimplementedGerenciaServer must be embedded to have forward compatible implementations.
type UnimplementedGerenciaServer struct {
}

func (UnimplementedGerenciaServer) RegistrarServidorGravacao(context.Context, *RegistrarServidorGravacaoReq) (*RegistrarServidorGravacaoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegistrarServidorGravacao not implemented")
}
func (UnimplementedGerenciaServer) DatabaseConfig(context.Context, *DatabaseConfigReq) (*DatabaseConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DatabaseConfig not implemented")
}
func (UnimplementedGerenciaServer) mustEmbedUnimplementedGerenciaServer() {}

// UnsafeGerenciaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GerenciaServer will
// result in compilation errors.
type UnsafeGerenciaServer interface {
	mustEmbedUnimplementedGerenciaServer()
}

func RegisterGerenciaServer(s grpc.ServiceRegistrar, srv GerenciaServer) {
	s.RegisterService(&Gerencia_ServiceDesc, srv)
}

func _Gerencia_RegistrarServidorGravacao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrarServidorGravacaoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GerenciaServer).RegistrarServidorGravacao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gerencia.Gerencia/RegistrarServidorGravacao",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GerenciaServer).RegistrarServidorGravacao(ctx, req.(*RegistrarServidorGravacaoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gerencia_DatabaseConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabaseConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GerenciaServer).DatabaseConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gerencia.Gerencia/DatabaseConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GerenciaServer).DatabaseConfig(ctx, req.(*DatabaseConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Gerencia_ServiceDesc is the grpc.ServiceDesc for Gerencia service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gerencia_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gerencia.Gerencia",
	HandlerType: (*GerenciaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegistrarServidorGravacao",
			Handler:    _Gerencia_RegistrarServidorGravacao_Handler,
		},
		{
			MethodName: "DatabaseConfig",
			Handler:    _Gerencia_DatabaseConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gerencia.proto",
}
