// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        v3.14.0
// source: gerencia.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistrarServidorGravacaoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Endereco string `protobuf:"bytes,2,opt,name=endereco,proto3" json:"endereco,omitempty"`
	Porta    int32  `protobuf:"varint,3,opt,name=porta,proto3" json:"porta,omitempty"`
}

func (x *RegistrarServidorGravacaoReq) Reset() {
	*x = RegistrarServidorGravacaoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrarServidorGravacaoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrarServidorGravacaoReq) ProtoMessage() {}

func (x *RegistrarServidorGravacaoReq) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrarServidorGravacaoReq.ProtoReflect.Descriptor instead.
func (*RegistrarServidorGravacaoReq) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrarServidorGravacaoReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegistrarServidorGravacaoReq) GetEndereco() string {
	if x != nil {
		return x.Endereco
	}
	return ""
}

func (x *RegistrarServidorGravacaoReq) GetPorta() int32 {
	if x != nil {
		return x.Porta
	}
	return 0
}

// TODO transformar em ENUM os status com informações pertinente
type RegistrarServidorGravacaoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RegistrarServidorGravacaoResp) Reset() {
	*x = RegistrarServidorGravacaoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrarServidorGravacaoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrarServidorGravacaoResp) ProtoMessage() {}

func (x *RegistrarServidorGravacaoResp) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrarServidorGravacaoResp.ProtoReflect.Descriptor instead.
func (*RegistrarServidorGravacaoResp) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrarServidorGravacaoResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegistrarServidorGravacaoResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ConfigBancoDeDadosReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfigBancoDeDadosReq) Reset() {
	*x = ConfigBancoDeDadosReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigBancoDeDadosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigBancoDeDadosReq) ProtoMessage() {}

func (x *ConfigBancoDeDadosReq) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigBancoDeDadosReq.ProtoReflect.Descriptor instead.
func (*ConfigBancoDeDadosReq) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{2}
}

type ConfigBancoDeDadosResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host         string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port         int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	User         string `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Password     string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Dbname       string `protobuf:"bytes,5,opt,name=dbname,proto3" json:"dbname,omitempty"`
	Poolmaxconns int32  `protobuf:"varint,6,opt,name=poolmaxconns,proto3" json:"poolmaxconns,omitempty"`
}

func (x *ConfigBancoDeDadosResp) Reset() {
	*x = ConfigBancoDeDadosResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigBancoDeDadosResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigBancoDeDadosResp) ProtoMessage() {}

func (x *ConfigBancoDeDadosResp) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigBancoDeDadosResp.ProtoReflect.Descriptor instead.
func (*ConfigBancoDeDadosResp) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigBancoDeDadosResp) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ConfigBancoDeDadosResp) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ConfigBancoDeDadosResp) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ConfigBancoDeDadosResp) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ConfigBancoDeDadosResp) GetDbname() string {
	if x != nil {
		return x.Dbname
	}
	return ""
}

func (x *ConfigBancoDeDadosResp) GetPoolmaxconns() int32 {
	if x != nil {
		return x.Poolmaxconns
	}
	return 0
}

var File_gerencia_proto protoreflect.FileDescriptor

var file_gerencia_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x22, 0x60, 0x0a, 0x1c, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47,
	0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x65, 0x63, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x65, 0x63, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x22, 0x47, 0x0a, 0x1d,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f,
	0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42,
	0x61, 0x6e, 0x63, 0x6f, 0x44, 0x65, 0x44, 0x61, 0x64, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x22, 0xac,
	0x01, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x61, 0x6e, 0x63, 0x6f, 0x44, 0x65,
	0x44, 0x61, 0x64, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x62, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x62, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x6f, 0x6f,
	0x6c, 0x6d, 0x61, 0x78, 0x63, 0x6f, 0x6e, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x70, 0x6f, 0x6f, 0x6c, 0x6d, 0x61, 0x78, 0x63, 0x6f, 0x6e, 0x6e, 0x73, 0x32, 0xd5, 0x01,
	0x0a, 0x08, 0x47, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x12, 0x6e, 0x0a, 0x19, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47,
	0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x12, 0x26, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x69, 0x61, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x65, 0x71, 0x1a,
	0x27, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76,
	0x61, 0x63, 0x61, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x12, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x42, 0x61, 0x6e, 0x63, 0x6f, 0x44, 0x65, 0x44, 0x61, 0x64, 0x6f, 0x73,
	0x12, 0x1f, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x42, 0x61, 0x6e, 0x63, 0x6f, 0x44, 0x65, 0x44, 0x61, 0x64, 0x6f, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x20, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x42, 0x61, 0x6e, 0x63, 0x6f, 0x44, 0x65, 0x44, 0x61, 0x64, 0x6f, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_gerencia_proto_rawDescOnce sync.Once
	file_gerencia_proto_rawDescData = file_gerencia_proto_rawDesc
)

func file_gerencia_proto_rawDescGZIP() []byte {
	file_gerencia_proto_rawDescOnce.Do(func() {
		file_gerencia_proto_rawDescData = protoimpl.X.CompressGZIP(file_gerencia_proto_rawDescData)
	})
	return file_gerencia_proto_rawDescData
}

var file_gerencia_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gerencia_proto_goTypes = []interface{}{
	(*RegistrarServidorGravacaoReq)(nil),  // 0: gerencia.RegistrarServidorGravacaoReq
	(*RegistrarServidorGravacaoResp)(nil), // 1: gerencia.RegistrarServidorGravacaoResp
	(*ConfigBancoDeDadosReq)(nil),         // 2: gerencia.ConfigBancoDeDadosReq
	(*ConfigBancoDeDadosResp)(nil),        // 3: gerencia.ConfigBancoDeDadosResp
}
var file_gerencia_proto_depIdxs = []int32{
	0, // 0: gerencia.Gerencia.RegistrarServidorGravacao:input_type -> gerencia.RegistrarServidorGravacaoReq
	2, // 1: gerencia.Gerencia.ConfigBancoDeDados:input_type -> gerencia.ConfigBancoDeDadosReq
	1, // 2: gerencia.Gerencia.RegistrarServidorGravacao:output_type -> gerencia.RegistrarServidorGravacaoResp
	3, // 3: gerencia.Gerencia.ConfigBancoDeDados:output_type -> gerencia.ConfigBancoDeDadosResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gerencia_proto_init() }
func file_gerencia_proto_init() {
	if File_gerencia_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gerencia_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrarServidorGravacaoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrarServidorGravacaoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigBancoDeDadosReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigBancoDeDadosResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gerencia_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gerencia_proto_goTypes,
		DependencyIndexes: file_gerencia_proto_depIdxs,
		MessageInfos:      file_gerencia_proto_msgTypes,
	}.Build()
	File_gerencia_proto = out.File
	file_gerencia_proto_rawDesc = nil
	file_gerencia_proto_goTypes = nil
	file_gerencia_proto_depIdxs = nil
}
