// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GravacaoClient is the client API for Gravacao service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GravacaoClient interface {
	Registrar(ctx context.Context, in *RegistrarReq, opts ...grpc.CallOption) (*RegistrarRes, error)
	RemoverRegistro(ctx context.Context, in *RemoverRegistroReq, opts ...grpc.CallOption) (*RemoverRegistroRes, error)
	AtualizarListaVeiculos(ctx context.Context, in *AtualizarListaVeiculosReq, opts ...grpc.CallOption) (*AtualizarListaVeiculosResp, error)
	CreateProcesso(ctx context.Context, in *CreateProcessoReq, opts ...grpc.CallOption) (*CreateProcessoRes, error)
	ReadProcesso(ctx context.Context, in *ReadProcessoReq, opts ...grpc.CallOption) (*ReadProcessoRes, error)
	ReadProcessos(ctx context.Context, in *ReadProcessosReq, opts ...grpc.CallOption) (*ReadProcessosRes, error)
	UpdateProcesso(ctx context.Context, in *UpdateProcessoReq, opts ...grpc.CallOption) (*UpdateProcessoRes, error)
	DeleteProcesso(ctx context.Context, in *DeleteProcessoReq, opts ...grpc.CallOption) (*DeleteProcessoRes, error)
}

type gravacaoClient struct {
	cc grpc.ClientConnInterface
}

func NewGravacaoClient(cc grpc.ClientConnInterface) GravacaoClient {
	return &gravacaoClient{cc}
}

func (c *gravacaoClient) Registrar(ctx context.Context, in *RegistrarReq, opts ...grpc.CallOption) (*RegistrarRes, error) {
	out := new(RegistrarRes)
	err := c.cc.Invoke(ctx, "/gravacao.Gravacao/Registrar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gravacaoClient) RemoverRegistro(ctx context.Context, in *RemoverRegistroReq, opts ...grpc.CallOption) (*RemoverRegistroRes, error) {
	out := new(RemoverRegistroRes)
	err := c.cc.Invoke(ctx, "/gravacao.Gravacao/RemoverRegistro", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gravacaoClient) AtualizarListaVeiculos(ctx context.Context, in *AtualizarListaVeiculosReq, opts ...grpc.CallOption) (*AtualizarListaVeiculosResp, error) {
	out := new(AtualizarListaVeiculosResp)
	err := c.cc.Invoke(ctx, "/gravacao.Gravacao/AtualizarListaVeiculos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gravacaoClient) CreateProcesso(ctx context.Context, in *CreateProcessoReq, opts ...grpc.CallOption) (*CreateProcessoRes, error) {
	out := new(CreateProcessoRes)
	err := c.cc.Invoke(ctx, "/gravacao.Gravacao/CreateProcesso", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gravacaoClient) ReadProcesso(ctx context.Context, in *ReadProcessoReq, opts ...grpc.CallOption) (*ReadProcessoRes, error) {
	out := new(ReadProcessoRes)
	err := c.cc.Invoke(ctx, "/gravacao.Gravacao/ReadProcesso", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gravacaoClient) ReadProcessos(ctx context.Context, in *ReadProcessosReq, opts ...grpc.CallOption) (*ReadProcessosRes, error) {
	out := new(ReadProcessosRes)
	err := c.cc.Invoke(ctx, "/gravacao.Gravacao/ReadProcessos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gravacaoClient) UpdateProcesso(ctx context.Context, in *UpdateProcessoReq, opts ...grpc.CallOption) (*UpdateProcessoRes, error) {
	out := new(UpdateProcessoRes)
	err := c.cc.Invoke(ctx, "/gravacao.Gravacao/UpdateProcesso", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gravacaoClient) DeleteProcesso(ctx context.Context, in *DeleteProcessoReq, opts ...grpc.CallOption) (*DeleteProcessoRes, error) {
	out := new(DeleteProcessoRes)
	err := c.cc.Invoke(ctx, "/gravacao.Gravacao/DeleteProcesso", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GravacaoServer is the server API for Gravacao service.
// All implementations must embed UnimplementedGravacaoServer
// for forward compatibility
type GravacaoServer interface {
	Registrar(context.Context, *RegistrarReq) (*RegistrarRes, error)
	RemoverRegistro(context.Context, *RemoverRegistroReq) (*RemoverRegistroRes, error)
	AtualizarListaVeiculos(context.Context, *AtualizarListaVeiculosReq) (*AtualizarListaVeiculosResp, error)
	CreateProcesso(context.Context, *CreateProcessoReq) (*CreateProcessoRes, error)
	ReadProcesso(context.Context, *ReadProcessoReq) (*ReadProcessoRes, error)
	ReadProcessos(context.Context, *ReadProcessosReq) (*ReadProcessosRes, error)
	UpdateProcesso(context.Context, *UpdateProcessoReq) (*UpdateProcessoRes, error)
	DeleteProcesso(context.Context, *DeleteProcessoReq) (*DeleteProcessoRes, error)
	mustEmbedUnimplementedGravacaoServer()
}

// UnimplementedGravacaoServer must be embedded to have forward compatible implementations.
type UnimplementedGravacaoServer struct {
}

func (UnimplementedGravacaoServer) Registrar(context.Context, *RegistrarReq) (*RegistrarRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Registrar not implemented")
}
func (UnimplementedGravacaoServer) RemoverRegistro(context.Context, *RemoverRegistroReq) (*RemoverRegistroRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoverRegistro not implemented")
}
func (UnimplementedGravacaoServer) AtualizarListaVeiculos(context.Context, *AtualizarListaVeiculosReq) (*AtualizarListaVeiculosResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AtualizarListaVeiculos not implemented")
}
func (UnimplementedGravacaoServer) CreateProcesso(context.Context, *CreateProcessoReq) (*CreateProcessoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProcesso not implemented")
}
func (UnimplementedGravacaoServer) ReadProcesso(context.Context, *ReadProcessoReq) (*ReadProcessoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadProcesso not implemented")
}
func (UnimplementedGravacaoServer) ReadProcessos(context.Context, *ReadProcessosReq) (*ReadProcessosRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadProcessos not implemented")
}
func (UnimplementedGravacaoServer) UpdateProcesso(context.Context, *UpdateProcessoReq) (*UpdateProcessoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProcesso not implemented")
}
func (UnimplementedGravacaoServer) DeleteProcesso(context.Context, *DeleteProcessoReq) (*DeleteProcessoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProcesso not implemented")
}
func (UnimplementedGravacaoServer) mustEmbedUnimplementedGravacaoServer() {}

// UnsafeGravacaoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GravacaoServer will
// result in compilation errors.
type UnsafeGravacaoServer interface {
	mustEmbedUnimplementedGravacaoServer()
}

func RegisterGravacaoServer(s grpc.ServiceRegistrar, srv GravacaoServer) {
	s.RegisterService(&Gravacao_ServiceDesc, srv)
}

func _Gravacao_Registrar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrarReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GravacaoServer).Registrar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravacao.Gravacao/Registrar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GravacaoServer).Registrar(ctx, req.(*RegistrarReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gravacao_RemoverRegistro_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoverRegistroReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GravacaoServer).RemoverRegistro(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravacao.Gravacao/RemoverRegistro",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GravacaoServer).RemoverRegistro(ctx, req.(*RemoverRegistroReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gravacao_AtualizarListaVeiculos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AtualizarListaVeiculosReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GravacaoServer).AtualizarListaVeiculos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravacao.Gravacao/AtualizarListaVeiculos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GravacaoServer).AtualizarListaVeiculos(ctx, req.(*AtualizarListaVeiculosReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gravacao_CreateProcesso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProcessoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GravacaoServer).CreateProcesso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravacao.Gravacao/CreateProcesso",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GravacaoServer).CreateProcesso(ctx, req.(*CreateProcessoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gravacao_ReadProcesso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadProcessoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GravacaoServer).ReadProcesso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravacao.Gravacao/ReadProcesso",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GravacaoServer).ReadProcesso(ctx, req.(*ReadProcessoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gravacao_ReadProcessos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadProcessosReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GravacaoServer).ReadProcessos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravacao.Gravacao/ReadProcessos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GravacaoServer).ReadProcessos(ctx, req.(*ReadProcessosReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gravacao_UpdateProcesso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProcessoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GravacaoServer).UpdateProcesso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravacao.Gravacao/UpdateProcesso",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GravacaoServer).UpdateProcesso(ctx, req.(*UpdateProcessoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gravacao_DeleteProcesso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProcessoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GravacaoServer).DeleteProcesso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravacao.Gravacao/DeleteProcesso",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GravacaoServer).DeleteProcesso(ctx, req.(*DeleteProcessoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Gravacao_ServiceDesc is the grpc.ServiceDesc for Gravacao service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gravacao_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gravacao.Gravacao",
	HandlerType: (*GravacaoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Registrar",
			Handler:    _Gravacao_Registrar_Handler,
		},
		{
			MethodName: "RemoverRegistro",
			Handler:    _Gravacao_RemoverRegistro_Handler,
		},
		{
			MethodName: "AtualizarListaVeiculos",
			Handler:    _Gravacao_AtualizarListaVeiculos_Handler,
		},
		{
			MethodName: "CreateProcesso",
			Handler:    _Gravacao_CreateProcesso_Handler,
		},
		{
			MethodName: "ReadProcesso",
			Handler:    _Gravacao_ReadProcesso_Handler,
		},
		{
			MethodName: "ReadProcessos",
			Handler:    _Gravacao_ReadProcessos_Handler,
		},
		{
			MethodName: "UpdateProcesso",
			Handler:    _Gravacao_UpdateProcesso_Handler,
		},
		{
			MethodName: "DeleteProcesso",
			Handler:    _Gravacao_DeleteProcesso_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gravacao.proto",
}
