// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        v3.18.0
// source: gravacao.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistrarReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnderecoIp     string `protobuf:"bytes,1,opt,name=endereco_ip,json=enderecoIp,proto3" json:"endereco_ip,omitempty"`
	Porta          int32  `protobuf:"varint,2,opt,name=porta,proto3" json:"porta,omitempty"`
	DbHost         string `protobuf:"bytes,3,opt,name=db_host,json=dbHost,proto3" json:"db_host,omitempty"`
	DbUser         string `protobuf:"bytes,4,opt,name=db_user,json=dbUser,proto3" json:"db_user,omitempty"`
	DbPassword     string `protobuf:"bytes,5,opt,name=db_password,json=dbPassword,proto3" json:"db_password,omitempty"`
	DbName         string `protobuf:"bytes,6,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	DbMaxidleconns int32  `protobuf:"varint,7,opt,name=db_maxidleconns,json=dbMaxidleconns,proto3" json:"db_maxidleconns,omitempty"`
	DbMaxopenconns int32  `protobuf:"varint,8,opt,name=db_maxopenconns,json=dbMaxopenconns,proto3" json:"db_maxopenconns,omitempty"`
	DbSslmode      string `protobuf:"bytes,9,opt,name=db_sslmode,json=dbSslmode,proto3" json:"db_sslmode,omitempty"`
}

func (x *RegistrarReq) Reset() {
	*x = RegistrarReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrarReq) ProtoMessage() {}

func (x *RegistrarReq) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrarReq.ProtoReflect.Descriptor instead.
func (*RegistrarReq) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrarReq) GetEnderecoIp() string {
	if x != nil {
		return x.EnderecoIp
	}
	return ""
}

func (x *RegistrarReq) GetPorta() int32 {
	if x != nil {
		return x.Porta
	}
	return 0
}

func (x *RegistrarReq) GetDbHost() string {
	if x != nil {
		return x.DbHost
	}
	return ""
}

func (x *RegistrarReq) GetDbUser() string {
	if x != nil {
		return x.DbUser
	}
	return ""
}

func (x *RegistrarReq) GetDbPassword() string {
	if x != nil {
		return x.DbPassword
	}
	return ""
}

func (x *RegistrarReq) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *RegistrarReq) GetDbMaxidleconns() int32 {
	if x != nil {
		return x.DbMaxidleconns
	}
	return 0
}

func (x *RegistrarReq) GetDbMaxopenconns() int32 {
	if x != nil {
		return x.DbMaxopenconns
	}
	return 0
}

func (x *RegistrarReq) GetDbSslmode() string {
	if x != nil {
		return x.DbSslmode
	}
	return ""
}

type RegistrarRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegistrarRes) Reset() {
	*x = RegistrarRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrarRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrarRes) ProtoMessage() {}

func (x *RegistrarRes) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrarRes.ProtoReflect.Descriptor instead.
func (*RegistrarRes) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{1}
}

type RemoverRegistroReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoverRegistroReq) Reset() {
	*x = RemoverRegistroReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoverRegistroReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoverRegistroReq) ProtoMessage() {}

func (x *RemoverRegistroReq) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoverRegistroReq.ProtoReflect.Descriptor instead.
func (*RemoverRegistroReq) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{2}
}

type RemoverRegistroRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoverRegistroRes) Reset() {
	*x = RemoverRegistroRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoverRegistroRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoverRegistroRes) ProtoMessage() {}

func (x *RemoverRegistroRes) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoverRegistroRes.ProtoReflect.Descriptor instead.
func (*RemoverRegistroRes) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{3}
}

type Processo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessoId         string `protobuf:"bytes,1,opt,name=processo_id,json=processoId,proto3" json:"processo_id,omitempty"`
	ServidorGravacaoId string `protobuf:"bytes,2,opt,name=servidor_gravacao_id,json=servidorGravacaoId,proto3" json:"servidor_gravacao_id,omitempty"`
	CameraId           string `protobuf:"bytes,3,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	Processador        int32  `protobuf:"varint,4,opt,name=processador,proto3" json:"processador,omitempty"`
	Adaptador          int32  `protobuf:"varint,5,opt,name=adaptador,proto3" json:"adaptador,omitempty"`
	Execucao           bool   `protobuf:"varint,6,opt,name=execucao,proto3" json:"execucao,omitempty"`
}

func (x *Processo) Reset() {
	*x = Processo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Processo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Processo) ProtoMessage() {}

func (x *Processo) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Processo.ProtoReflect.Descriptor instead.
func (*Processo) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{4}
}

func (x *Processo) GetProcessoId() string {
	if x != nil {
		return x.ProcessoId
	}
	return ""
}

func (x *Processo) GetServidorGravacaoId() string {
	if x != nil {
		return x.ServidorGravacaoId
	}
	return ""
}

func (x *Processo) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *Processo) GetProcessador() int32 {
	if x != nil {
		return x.Processador
	}
	return 0
}

func (x *Processo) GetAdaptador() int32 {
	if x != nil {
		return x.Adaptador
	}
	return 0
}

func (x *Processo) GetExecucao() bool {
	if x != nil {
		return x.Execucao
	}
	return false
}

type CreateProcessoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Processo *Processo `protobuf:"bytes,1,opt,name=processo,proto3" json:"processo,omitempty"`
}

func (x *CreateProcessoReq) Reset() {
	*x = CreateProcessoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateProcessoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProcessoReq) ProtoMessage() {}

func (x *CreateProcessoReq) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProcessoReq.ProtoReflect.Descriptor instead.
func (*CreateProcessoReq) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{5}
}

func (x *CreateProcessoReq) GetProcesso() *Processo {
	if x != nil {
		return x.Processo
	}
	return nil
}

type CreateProcessoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessoId string `protobuf:"bytes,1,opt,name=processo_id,json=processoId,proto3" json:"processo_id,omitempty"`
}

func (x *CreateProcessoRes) Reset() {
	*x = CreateProcessoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateProcessoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProcessoRes) ProtoMessage() {}

func (x *CreateProcessoRes) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProcessoRes.ProtoReflect.Descriptor instead.
func (*CreateProcessoRes) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{6}
}

func (x *CreateProcessoRes) GetProcessoId() string {
	if x != nil {
		return x.ProcessoId
	}
	return ""
}

type ReadProcessoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessoId string `protobuf:"bytes,1,opt,name=processo_id,json=processoId,proto3" json:"processo_id,omitempty"`
}

func (x *ReadProcessoReq) Reset() {
	*x = ReadProcessoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadProcessoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadProcessoReq) ProtoMessage() {}

func (x *ReadProcessoReq) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadProcessoReq.ProtoReflect.Descriptor instead.
func (*ReadProcessoReq) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{7}
}

func (x *ReadProcessoReq) GetProcessoId() string {
	if x != nil {
		return x.ProcessoId
	}
	return ""
}

type ReadProcessoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Processo *Processo `protobuf:"bytes,1,opt,name=processo,proto3" json:"processo,omitempty"`
}

func (x *ReadProcessoRes) Reset() {
	*x = ReadProcessoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadProcessoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadProcessoRes) ProtoMessage() {}

func (x *ReadProcessoRes) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadProcessoRes.ProtoReflect.Descriptor instead.
func (*ReadProcessoRes) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{8}
}

func (x *ReadProcessoRes) GetProcesso() *Processo {
	if x != nil {
		return x.Processo
	}
	return nil
}

type ReadProcessosReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadProcessosReq) Reset() {
	*x = ReadProcessosReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadProcessosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadProcessosReq) ProtoMessage() {}

func (x *ReadProcessosReq) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadProcessosReq.ProtoReflect.Descriptor instead.
func (*ReadProcessosReq) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{9}
}

type ReadProcessosRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Processos []*Processo `protobuf:"bytes,1,rep,name=processos,proto3" json:"processos,omitempty"`
}

func (x *ReadProcessosRes) Reset() {
	*x = ReadProcessosRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadProcessosRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadProcessosRes) ProtoMessage() {}

func (x *ReadProcessosRes) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadProcessosRes.ProtoReflect.Descriptor instead.
func (*ReadProcessosRes) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{10}
}

func (x *ReadProcessosRes) GetProcessos() []*Processo {
	if x != nil {
		return x.Processos
	}
	return nil
}

type UpdateProcessoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Processo *Processo `protobuf:"bytes,1,opt,name=processo,proto3" json:"processo,omitempty"`
}

func (x *UpdateProcessoReq) Reset() {
	*x = UpdateProcessoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProcessoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProcessoReq) ProtoMessage() {}

func (x *UpdateProcessoReq) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProcessoReq.ProtoReflect.Descriptor instead.
func (*UpdateProcessoReq) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateProcessoReq) GetProcesso() *Processo {
	if x != nil {
		return x.Processo
	}
	return nil
}

type UpdateProcessoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateProcessoRes) Reset() {
	*x = UpdateProcessoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProcessoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProcessoRes) ProtoMessage() {}

func (x *UpdateProcessoRes) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProcessoRes.ProtoReflect.Descriptor instead.
func (*UpdateProcessoRes) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{12}
}

type DeleteProcessoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessoId string `protobuf:"bytes,1,opt,name=processo_id,json=processoId,proto3" json:"processo_id,omitempty"`
}

func (x *DeleteProcessoReq) Reset() {
	*x = DeleteProcessoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProcessoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProcessoReq) ProtoMessage() {}

func (x *DeleteProcessoReq) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProcessoReq.ProtoReflect.Descriptor instead.
func (*DeleteProcessoReq) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteProcessoReq) GetProcessoId() string {
	if x != nil {
		return x.ProcessoId
	}
	return ""
}

type DeleteProcessoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteProcessoRes) Reset() {
	*x = DeleteProcessoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProcessoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProcessoRes) ProtoMessage() {}

func (x *DeleteProcessoRes) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProcessoRes.ProtoReflect.Descriptor instead.
func (*DeleteProcessoRes) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{14}
}

type AtualizarListaVeiculosReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Veiculo []*AtualizarListaVeiculosReq_Veiculo `protobuf:"bytes,1,rep,name=veiculo,proto3" json:"veiculo,omitempty"`
}

func (x *AtualizarListaVeiculosReq) Reset() {
	*x = AtualizarListaVeiculosReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtualizarListaVeiculosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtualizarListaVeiculosReq) ProtoMessage() {}

func (x *AtualizarListaVeiculosReq) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtualizarListaVeiculosReq.ProtoReflect.Descriptor instead.
func (*AtualizarListaVeiculosReq) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{15}
}

func (x *AtualizarListaVeiculosReq) GetVeiculo() []*AtualizarListaVeiculosReq_Veiculo {
	if x != nil {
		return x.Veiculo
	}
	return nil
}

type AtualizarListaVeiculosResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AtualizarListaVeiculosResp) Reset() {
	*x = AtualizarListaVeiculosResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtualizarListaVeiculosResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtualizarListaVeiculosResp) ProtoMessage() {}

func (x *AtualizarListaVeiculosResp) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtualizarListaVeiculosResp.ProtoReflect.Descriptor instead.
func (*AtualizarListaVeiculosResp) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{16}
}

type AtualizarListaVeiculosReq_Veiculo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Placa  string `protobuf:"bytes,1,opt,name=placa,proto3" json:"placa,omitempty"`
	Cor    string `protobuf:"bytes,2,opt,name=cor,proto3" json:"cor,omitempty"`
	Marca  string `protobuf:"bytes,3,opt,name=marca,proto3" json:"marca,omitempty"`
	Modelo string `protobuf:"bytes,4,opt,name=modelo,proto3" json:"modelo,omitempty"`
	Tipo   string `protobuf:"bytes,5,opt,name=tipo,proto3" json:"tipo,omitempty"`
}

func (x *AtualizarListaVeiculosReq_Veiculo) Reset() {
	*x = AtualizarListaVeiculosReq_Veiculo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gravacao_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtualizarListaVeiculosReq_Veiculo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtualizarListaVeiculosReq_Veiculo) ProtoMessage() {}

func (x *AtualizarListaVeiculosReq_Veiculo) ProtoReflect() protoreflect.Message {
	mi := &file_gravacao_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtualizarListaVeiculosReq_Veiculo.ProtoReflect.Descriptor instead.
func (*AtualizarListaVeiculosReq_Veiculo) Descriptor() ([]byte, []int) {
	return file_gravacao_proto_rawDescGZIP(), []int{15, 0}
}

func (x *AtualizarListaVeiculosReq_Veiculo) GetPlaca() string {
	if x != nil {
		return x.Placa
	}
	return ""
}

func (x *AtualizarListaVeiculosReq_Veiculo) GetCor() string {
	if x != nil {
		return x.Cor
	}
	return ""
}

func (x *AtualizarListaVeiculosReq_Veiculo) GetMarca() string {
	if x != nil {
		return x.Marca
	}
	return ""
}

func (x *AtualizarListaVeiculosReq_Veiculo) GetModelo() string {
	if x != nil {
		return x.Modelo
	}
	return ""
}

func (x *AtualizarListaVeiculosReq_Veiculo) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

var File_gravacao_proto protoreflect.FileDescriptor

var file_gravacao_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x22, 0xa2, 0x02, 0x0a, 0x0c, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x65, 0x63, 0x6f, 0x5f, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x65, 0x63, 0x6f, 0x49, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x6f, 0x72, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x6f, 0x72,
	0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x62, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x62, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x64,
	0x62, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x62,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x62, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x62, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27,
	0x0a, 0x0f, 0x64, 0x62, 0x5f, 0x6d, 0x61, 0x78, 0x69, 0x64, 0x6c, 0x65, 0x63, 0x6f, 0x6e, 0x6e,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x64, 0x62, 0x4d, 0x61, 0x78, 0x69, 0x64,
	0x6c, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x64, 0x62, 0x5f, 0x6d, 0x61,
	0x78, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x6e, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0e, 0x64, 0x62, 0x4d, 0x61, 0x78, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x6e, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x62, 0x5f, 0x73, 0x73, 0x6c, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x62, 0x53, 0x73, 0x6c, 0x6d, 0x6f, 0x64, 0x65, 0x22,
	0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x52, 0x65, 0x73, 0x22,
	0x14, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x6f, 0x52, 0x65, 0x71, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x22, 0xd6, 0x01, 0x0a, 0x08,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x14, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x64, 0x6f, 0x72, 0x5f, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f,
	0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x61, 0x6d, 0x65, 0x72, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x64,
	0x61, 0x70, 0x74, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61,
	0x64, 0x61, 0x70, 0x74, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x65, 0x63,
	0x75, 0x63, 0x61, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x65, 0x78, 0x65, 0x63,
	0x75, 0x63, 0x61, 0x6f, 0x22, 0x43, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x2e, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x72,
	0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52,
	0x08, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x22, 0x34, 0x0a, 0x11, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x49, 0x64, 0x22,
	0x32, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52,
	0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61,
	0x63, 0x61, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x22, 0x12, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x22, 0x44, 0x0a, 0x10, 0x52, 0x65,
	0x61, 0x64, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x12, 0x30,
	0x0a, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73,
	0x22, 0x43, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x2e, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63,
	0x61, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x34, 0x0a, 0x11, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x71, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x49, 0x64,
	0x22, 0x13, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x52, 0x65, 0x73, 0x22, 0xd7, 0x01, 0x0a, 0x19, 0x41, 0x74, 0x75, 0x61, 0x6c, 0x69,
	0x7a, 0x61, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x56, 0x65, 0x69, 0x63, 0x75, 0x6c, 0x6f, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x45, 0x0a, 0x07, 0x76, 0x65, 0x69, 0x63, 0x75, 0x6c, 0x6f, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e,
	0x41, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x56, 0x65,
	0x69, 0x63, 0x75, 0x6c, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x2e, 0x56, 0x65, 0x69, 0x63, 0x75, 0x6c,
	0x6f, 0x52, 0x07, 0x76, 0x65, 0x69, 0x63, 0x75, 0x6c, 0x6f, 0x1a, 0x73, 0x0a, 0x07, 0x56, 0x65,
	0x69, 0x63, 0x75, 0x6c, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x63,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6f, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x61, 0x72, 0x63, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x61,
	0x72, 0x63, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x70, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x22,
	0x1c, 0x0a, 0x1a, 0x41, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x61, 0x56, 0x65, 0x69, 0x63, 0x75, 0x6c, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x32, 0xfe, 0x04,
	0x0a, 0x08, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x12, 0x3d, 0x0a, 0x09, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x12, 0x16, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63,
	0x61, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x16, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x72, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0f, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x12, 0x1c, 0x2e, 0x67,
	0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x67, 0x72, 0x61,
	0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x65, 0x0a, 0x16, 0x41, 0x74,
	0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x56, 0x65, 0x69, 0x63,
	0x75, 0x6c, 0x6f, 0x73, 0x12, 0x23, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e,
	0x41, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x56, 0x65,
	0x69, 0x63, 0x75, 0x6c, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x67, 0x72, 0x61, 0x76,
	0x61, 0x63, 0x61, 0x6f, 0x2e, 0x41, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x61, 0x56, 0x65, 0x69, 0x63, 0x75, 0x6c, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x4c, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x12, 0x1b, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x71,
	0x1a, 0x1b, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x46, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x12,
	0x19, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x67, 0x72, 0x61,
	0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0d, 0x52, 0x65, 0x61, 0x64, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73, 0x12, 0x1a, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61,
	0x63, 0x61, 0x6f, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x73, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x12, 0x1b, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65,
	0x71, 0x1a, 0x1b, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x4c, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x12, 0x1b, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x71, 0x1a,
	0x1b, 0x2e, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x13,
	0x5a, 0x11, 0x2e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gravacao_proto_rawDescOnce sync.Once
	file_gravacao_proto_rawDescData = file_gravacao_proto_rawDesc
)

func file_gravacao_proto_rawDescGZIP() []byte {
	file_gravacao_proto_rawDescOnce.Do(func() {
		file_gravacao_proto_rawDescData = protoimpl.X.CompressGZIP(file_gravacao_proto_rawDescData)
	})
	return file_gravacao_proto_rawDescData
}

var file_gravacao_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_gravacao_proto_goTypes = []interface{}{
	(*RegistrarReq)(nil),                      // 0: gravacao.RegistrarReq
	(*RegistrarRes)(nil),                      // 1: gravacao.RegistrarRes
	(*RemoverRegistroReq)(nil),                // 2: gravacao.RemoverRegistroReq
	(*RemoverRegistroRes)(nil),                // 3: gravacao.RemoverRegistroRes
	(*Processo)(nil),                          // 4: gravacao.Processo
	(*CreateProcessoReq)(nil),                 // 5: gravacao.CreateProcessoReq
	(*CreateProcessoRes)(nil),                 // 6: gravacao.CreateProcessoRes
	(*ReadProcessoReq)(nil),                   // 7: gravacao.ReadProcessoReq
	(*ReadProcessoRes)(nil),                   // 8: gravacao.ReadProcessoRes
	(*ReadProcessosReq)(nil),                  // 9: gravacao.ReadProcessosReq
	(*ReadProcessosRes)(nil),                  // 10: gravacao.ReadProcessosRes
	(*UpdateProcessoReq)(nil),                 // 11: gravacao.UpdateProcessoReq
	(*UpdateProcessoRes)(nil),                 // 12: gravacao.UpdateProcessoRes
	(*DeleteProcessoReq)(nil),                 // 13: gravacao.DeleteProcessoReq
	(*DeleteProcessoRes)(nil),                 // 14: gravacao.DeleteProcessoRes
	(*AtualizarListaVeiculosReq)(nil),         // 15: gravacao.AtualizarListaVeiculosReq
	(*AtualizarListaVeiculosResp)(nil),        // 16: gravacao.AtualizarListaVeiculosResp
	(*AtualizarListaVeiculosReq_Veiculo)(nil), // 17: gravacao.AtualizarListaVeiculosReq.Veiculo
}
var file_gravacao_proto_depIdxs = []int32{
	4,  // 0: gravacao.CreateProcessoReq.processo:type_name -> gravacao.Processo
	4,  // 1: gravacao.ReadProcessoRes.processo:type_name -> gravacao.Processo
	4,  // 2: gravacao.ReadProcessosRes.processos:type_name -> gravacao.Processo
	4,  // 3: gravacao.UpdateProcessoReq.processo:type_name -> gravacao.Processo
	17, // 4: gravacao.AtualizarListaVeiculosReq.veiculo:type_name -> gravacao.AtualizarListaVeiculosReq.Veiculo
	0,  // 5: gravacao.Gravacao.Registrar:input_type -> gravacao.RegistrarReq
	2,  // 6: gravacao.Gravacao.RemoverRegistro:input_type -> gravacao.RemoverRegistroReq
	15, // 7: gravacao.Gravacao.AtualizarListaVeiculos:input_type -> gravacao.AtualizarListaVeiculosReq
	5,  // 8: gravacao.Gravacao.CreateProcesso:input_type -> gravacao.CreateProcessoReq
	7,  // 9: gravacao.Gravacao.ReadProcesso:input_type -> gravacao.ReadProcessoReq
	9,  // 10: gravacao.Gravacao.ReadProcessos:input_type -> gravacao.ReadProcessosReq
	11, // 11: gravacao.Gravacao.UpdateProcesso:input_type -> gravacao.UpdateProcessoReq
	13, // 12: gravacao.Gravacao.DeleteProcesso:input_type -> gravacao.DeleteProcessoReq
	1,  // 13: gravacao.Gravacao.Registrar:output_type -> gravacao.RegistrarRes
	3,  // 14: gravacao.Gravacao.RemoverRegistro:output_type -> gravacao.RemoverRegistroRes
	16, // 15: gravacao.Gravacao.AtualizarListaVeiculos:output_type -> gravacao.AtualizarListaVeiculosResp
	6,  // 16: gravacao.Gravacao.CreateProcesso:output_type -> gravacao.CreateProcessoRes
	8,  // 17: gravacao.Gravacao.ReadProcesso:output_type -> gravacao.ReadProcessoRes
	10, // 18: gravacao.Gravacao.ReadProcessos:output_type -> gravacao.ReadProcessosRes
	12, // 19: gravacao.Gravacao.UpdateProcesso:output_type -> gravacao.UpdateProcessoRes
	14, // 20: gravacao.Gravacao.DeleteProcesso:output_type -> gravacao.DeleteProcessoRes
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_gravacao_proto_init() }
func file_gravacao_proto_init() {
	if File_gravacao_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gravacao_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrarReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrarRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoverRegistroReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoverRegistroRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Processo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateProcessoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateProcessoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadProcessoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadProcessoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadProcessosReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadProcessosRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProcessoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProcessoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteProcessoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteProcessoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AtualizarListaVeiculosReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AtualizarListaVeiculosResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gravacao_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AtualizarListaVeiculosReq_Veiculo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gravacao_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gravacao_proto_goTypes,
		DependencyIndexes: file_gravacao_proto_depIdxs,
		MessageInfos:      file_gravacao_proto_msgTypes,
	}.Build()
	File_gravacao_proto = out.File
	file_gravacao_proto_rawDesc = nil
	file_gravacao_proto_goTypes = nil
	file_gravacao_proto_depIdxs = nil
}
