// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        v3.18.0
// source: gerencia.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegistroId string `protobuf:"bytes,1,opt,name=registro_id,json=registroId,proto3" json:"registro_id,omitempty"`
	PlacaId    string `protobuf:"bytes,2,opt,name=placa_id,json=placaId,proto3" json:"placa_id,omitempty"`
}

func (x *MatchReq) Reset() {
	*x = MatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchReq) ProtoMessage() {}

func (x *MatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchReq.ProtoReflect.Descriptor instead.
func (*MatchReq) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{0}
}

func (x *MatchReq) GetRegistroId() string {
	if x != nil {
		return x.RegistroId
	}
	return ""
}

func (x *MatchReq) GetPlacaId() string {
	if x != nil {
		return x.PlacaId
	}
	return ""
}

type MatchRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MatchRes) Reset() {
	*x = MatchRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRes) ProtoMessage() {}

func (x *MatchRes) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRes.ProtoReflect.Descriptor instead.
func (*MatchRes) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{1}
}

type MigrateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Versao int32 `protobuf:"varint,1,opt,name=versao,proto3" json:"versao,omitempty"`
}

func (x *MigrateReq) Reset() {
	*x = MigrateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateReq) ProtoMessage() {}

func (x *MigrateReq) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateReq.ProtoReflect.Descriptor instead.
func (*MigrateReq) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{2}
}

func (x *MigrateReq) GetVersao() int32 {
	if x != nil {
		return x.Versao
	}
	return 0
}

type MigrateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MigrateRes) Reset() {
	*x = MigrateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateRes) ProtoMessage() {}

func (x *MigrateRes) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateRes.ProtoReflect.Descriptor instead.
func (*MigrateRes) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{3}
}

type ServidorGravacao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServidorGravacaoId string                 `protobuf:"bytes,1,opt,name=servidor_gravacao_id,json=servidorGravacaoId,proto3" json:"servidor_gravacao_id,omitempty"`
	EnderecoIp         string                 `protobuf:"bytes,2,opt,name=endereco_ip,json=enderecoIp,proto3" json:"endereco_ip,omitempty"`
	Porta              int32                  `protobuf:"varint,3,opt,name=porta,proto3" json:"porta,omitempty"`
	Host               string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	CriadoEm           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=criado_em,json=criadoEm,proto3" json:"criado_em,omitempty"`
	EditadoEm          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=editado_em,json=editadoEm,proto3" json:"editado_em,omitempty"`
}

func (x *ServidorGravacao) Reset() {
	*x = ServidorGravacao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServidorGravacao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServidorGravacao) ProtoMessage() {}

func (x *ServidorGravacao) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServidorGravacao.ProtoReflect.Descriptor instead.
func (*ServidorGravacao) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{4}
}

func (x *ServidorGravacao) GetServidorGravacaoId() string {
	if x != nil {
		return x.ServidorGravacaoId
	}
	return ""
}

func (x *ServidorGravacao) GetEnderecoIp() string {
	if x != nil {
		return x.EnderecoIp
	}
	return ""
}

func (x *ServidorGravacao) GetPorta() int32 {
	if x != nil {
		return x.Porta
	}
	return 0
}

func (x *ServidorGravacao) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServidorGravacao) GetCriadoEm() *timestamppb.Timestamp {
	if x != nil {
		return x.CriadoEm
	}
	return nil
}

func (x *ServidorGravacao) GetEditadoEm() *timestamppb.Timestamp {
	if x != nil {
		return x.EditadoEm
	}
	return nil
}

type CreateServidorGravacaoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServidorGravacao *ServidorGravacao `protobuf:"bytes,1,opt,name=servidor_gravacao,json=servidorGravacao,proto3" json:"servidor_gravacao,omitempty"`
}

func (x *CreateServidorGravacaoReq) Reset() {
	*x = CreateServidorGravacaoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateServidorGravacaoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServidorGravacaoReq) ProtoMessage() {}

func (x *CreateServidorGravacaoReq) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServidorGravacaoReq.ProtoReflect.Descriptor instead.
func (*CreateServidorGravacaoReq) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{5}
}

func (x *CreateServidorGravacaoReq) GetServidorGravacao() *ServidorGravacao {
	if x != nil {
		return x.ServidorGravacao
	}
	return nil
}

type CreateServidorGravacaoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServidorGravacao *ServidorGravacao `protobuf:"bytes,1,opt,name=servidor_gravacao,json=servidorGravacao,proto3" json:"servidor_gravacao,omitempty"`
}

func (x *CreateServidorGravacaoRes) Reset() {
	*x = CreateServidorGravacaoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateServidorGravacaoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServidorGravacaoRes) ProtoMessage() {}

func (x *CreateServidorGravacaoRes) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServidorGravacaoRes.ProtoReflect.Descriptor instead.
func (*CreateServidorGravacaoRes) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{6}
}

func (x *CreateServidorGravacaoRes) GetServidorGravacao() *ServidorGravacao {
	if x != nil {
		return x.ServidorGravacao
	}
	return nil
}

type ReadServidorGravacaoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServidorGravacao *ServidorGravacao `protobuf:"bytes,1,opt,name=servidor_gravacao,json=servidorGravacao,proto3" json:"servidor_gravacao,omitempty"`
}

func (x *ReadServidorGravacaoReq) Reset() {
	*x = ReadServidorGravacaoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadServidorGravacaoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadServidorGravacaoReq) ProtoMessage() {}

func (x *ReadServidorGravacaoReq) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadServidorGravacaoReq.ProtoReflect.Descriptor instead.
func (*ReadServidorGravacaoReq) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{7}
}

func (x *ReadServidorGravacaoReq) GetServidorGravacao() *ServidorGravacao {
	if x != nil {
		return x.ServidorGravacao
	}
	return nil
}

type ReadServidorGravacaoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServidorGravacao *ServidorGravacao `protobuf:"bytes,1,opt,name=servidor_gravacao,json=servidorGravacao,proto3" json:"servidor_gravacao,omitempty"`
}

func (x *ReadServidorGravacaoRes) Reset() {
	*x = ReadServidorGravacaoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadServidorGravacaoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadServidorGravacaoRes) ProtoMessage() {}

func (x *ReadServidorGravacaoRes) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadServidorGravacaoRes.ProtoReflect.Descriptor instead.
func (*ReadServidorGravacaoRes) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{8}
}

func (x *ReadServidorGravacaoRes) GetServidorGravacao() *ServidorGravacao {
	if x != nil {
		return x.ServidorGravacao
	}
	return nil
}

type UpdateServidorGravacaoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServidorGravacao *ServidorGravacao `protobuf:"bytes,1,opt,name=servidor_gravacao,json=servidorGravacao,proto3" json:"servidor_gravacao,omitempty"`
}

func (x *UpdateServidorGravacaoReq) Reset() {
	*x = UpdateServidorGravacaoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateServidorGravacaoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServidorGravacaoReq) ProtoMessage() {}

func (x *UpdateServidorGravacaoReq) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServidorGravacaoReq.ProtoReflect.Descriptor instead.
func (*UpdateServidorGravacaoReq) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateServidorGravacaoReq) GetServidorGravacao() *ServidorGravacao {
	if x != nil {
		return x.ServidorGravacao
	}
	return nil
}

type UpdateServidorGravacaoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServidorGravacao *ServidorGravacao `protobuf:"bytes,1,opt,name=servidor_gravacao,json=servidorGravacao,proto3" json:"servidor_gravacao,omitempty"`
}

func (x *UpdateServidorGravacaoRes) Reset() {
	*x = UpdateServidorGravacaoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateServidorGravacaoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServidorGravacaoRes) ProtoMessage() {}

func (x *UpdateServidorGravacaoRes) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServidorGravacaoRes.ProtoReflect.Descriptor instead.
func (*UpdateServidorGravacaoRes) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateServidorGravacaoRes) GetServidorGravacao() *ServidorGravacao {
	if x != nil {
		return x.ServidorGravacao
	}
	return nil
}

type DeleteServidorGravacaoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServidorGravacao *ServidorGravacao `protobuf:"bytes,1,opt,name=servidor_gravacao,json=servidorGravacao,proto3" json:"servidor_gravacao,omitempty"`
}

func (x *DeleteServidorGravacaoReq) Reset() {
	*x = DeleteServidorGravacaoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteServidorGravacaoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServidorGravacaoReq) ProtoMessage() {}

func (x *DeleteServidorGravacaoReq) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServidorGravacaoReq.ProtoReflect.Descriptor instead.
func (*DeleteServidorGravacaoReq) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteServidorGravacaoReq) GetServidorGravacao() *ServidorGravacao {
	if x != nil {
		return x.ServidorGravacao
	}
	return nil
}

type DeleteServidorGravacaoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServidorGravacao *ServidorGravacao `protobuf:"bytes,1,opt,name=servidor_gravacao,json=servidorGravacao,proto3" json:"servidor_gravacao,omitempty"`
}

func (x *DeleteServidorGravacaoRes) Reset() {
	*x = DeleteServidorGravacaoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteServidorGravacaoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServidorGravacaoRes) ProtoMessage() {}

func (x *DeleteServidorGravacaoRes) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServidorGravacaoRes.ProtoReflect.Descriptor instead.
func (*DeleteServidorGravacaoRes) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteServidorGravacaoRes) GetServidorGravacao() *ServidorGravacao {
	if x != nil {
		return x.ServidorGravacao
	}
	return nil
}

type Camera struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CameraId       string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	Descricao      string                 `protobuf:"bytes,2,opt,name=descricao,proto3" json:"descricao,omitempty"`
	EnderecoIp     string                 `protobuf:"bytes,3,opt,name=endereco_ip,json=enderecoIp,proto3" json:"endereco_ip,omitempty"`
	Porta          int32                  `protobuf:"varint,4,opt,name=porta,proto3" json:"porta,omitempty"`
	Canal          int32                  `protobuf:"varint,5,opt,name=canal,proto3" json:"canal,omitempty"`
	Usuario        string                 `protobuf:"bytes,6,opt,name=usuario,proto3" json:"usuario,omitempty"`
	Senha          string                 `protobuf:"bytes,7,opt,name=senha,proto3" json:"senha,omitempty"`
	Geolocalizacao string                 `protobuf:"bytes,8,opt,name=geolocalizacao,proto3" json:"geolocalizacao,omitempty"`
	CriadoEm       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=criado_em,json=criadoEm,proto3" json:"criado_em,omitempty"`
	EditadoEm      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=editado_em,json=editadoEm,proto3" json:"editado_em,omitempty"`
}

func (x *Camera) Reset() {
	*x = Camera{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Camera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Camera) ProtoMessage() {}

func (x *Camera) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Camera.ProtoReflect.Descriptor instead.
func (*Camera) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{13}
}

func (x *Camera) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *Camera) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

func (x *Camera) GetEnderecoIp() string {
	if x != nil {
		return x.EnderecoIp
	}
	return ""
}

func (x *Camera) GetPorta() int32 {
	if x != nil {
		return x.Porta
	}
	return 0
}

func (x *Camera) GetCanal() int32 {
	if x != nil {
		return x.Canal
	}
	return 0
}

func (x *Camera) GetUsuario() string {
	if x != nil {
		return x.Usuario
	}
	return ""
}

func (x *Camera) GetSenha() string {
	if x != nil {
		return x.Senha
	}
	return ""
}

func (x *Camera) GetGeolocalizacao() string {
	if x != nil {
		return x.Geolocalizacao
	}
	return ""
}

func (x *Camera) GetCriadoEm() *timestamppb.Timestamp {
	if x != nil {
		return x.CriadoEm
	}
	return nil
}

func (x *Camera) GetEditadoEm() *timestamppb.Timestamp {
	if x != nil {
		return x.EditadoEm
	}
	return nil
}

type CreateCameraReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Camera *Camera `protobuf:"bytes,1,opt,name=camera,proto3" json:"camera,omitempty"`
}

func (x *CreateCameraReq) Reset() {
	*x = CreateCameraReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCameraReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCameraReq) ProtoMessage() {}

func (x *CreateCameraReq) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCameraReq.ProtoReflect.Descriptor instead.
func (*CreateCameraReq) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{14}
}

func (x *CreateCameraReq) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

type CreateCameraRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Camera *Camera `protobuf:"bytes,1,opt,name=camera,proto3" json:"camera,omitempty"`
}

func (x *CreateCameraRes) Reset() {
	*x = CreateCameraRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCameraRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCameraRes) ProtoMessage() {}

func (x *CreateCameraRes) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCameraRes.ProtoReflect.Descriptor instead.
func (*CreateCameraRes) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{15}
}

func (x *CreateCameraRes) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

type ReadCameraReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Camera *Camera `protobuf:"bytes,1,opt,name=camera,proto3" json:"camera,omitempty"`
}

func (x *ReadCameraReq) Reset() {
	*x = ReadCameraReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadCameraReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCameraReq) ProtoMessage() {}

func (x *ReadCameraReq) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCameraReq.ProtoReflect.Descriptor instead.
func (*ReadCameraReq) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{16}
}

func (x *ReadCameraReq) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

type ReadCameraRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Camera *Camera `protobuf:"bytes,1,opt,name=camera,proto3" json:"camera,omitempty"`
}

func (x *ReadCameraRes) Reset() {
	*x = ReadCameraRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadCameraRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCameraRes) ProtoMessage() {}

func (x *ReadCameraRes) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCameraRes.ProtoReflect.Descriptor instead.
func (*ReadCameraRes) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{17}
}

func (x *ReadCameraRes) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

type ReadCamerasReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Camera *Camera `protobuf:"bytes,1,opt,name=camera,proto3" json:"camera,omitempty"`
}

func (x *ReadCamerasReq) Reset() {
	*x = ReadCamerasReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadCamerasReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCamerasReq) ProtoMessage() {}

func (x *ReadCamerasReq) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCamerasReq.ProtoReflect.Descriptor instead.
func (*ReadCamerasReq) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{18}
}

func (x *ReadCamerasReq) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

type ReadCamerasRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cameras []*Camera `protobuf:"bytes,1,rep,name=cameras,proto3" json:"cameras,omitempty"`
}

func (x *ReadCamerasRes) Reset() {
	*x = ReadCamerasRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadCamerasRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCamerasRes) ProtoMessage() {}

func (x *ReadCamerasRes) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCamerasRes.ProtoReflect.Descriptor instead.
func (*ReadCamerasRes) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{19}
}

func (x *ReadCamerasRes) GetCameras() []*Camera {
	if x != nil {
		return x.Cameras
	}
	return nil
}

type UpdateCameraReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Camera *Camera `protobuf:"bytes,1,opt,name=camera,proto3" json:"camera,omitempty"`
}

func (x *UpdateCameraReq) Reset() {
	*x = UpdateCameraReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCameraReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCameraReq) ProtoMessage() {}

func (x *UpdateCameraReq) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCameraReq.ProtoReflect.Descriptor instead.
func (*UpdateCameraReq) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateCameraReq) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

type UpdateCameraRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Camera *Camera `protobuf:"bytes,1,opt,name=camera,proto3" json:"camera,omitempty"`
}

func (x *UpdateCameraRes) Reset() {
	*x = UpdateCameraRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCameraRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCameraRes) ProtoMessage() {}

func (x *UpdateCameraRes) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCameraRes.ProtoReflect.Descriptor instead.
func (*UpdateCameraRes) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateCameraRes) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

type DeleteCameraReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Camera *Camera `protobuf:"bytes,1,opt,name=camera,proto3" json:"camera,omitempty"`
}

func (x *DeleteCameraReq) Reset() {
	*x = DeleteCameraReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCameraReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCameraReq) ProtoMessage() {}

func (x *DeleteCameraReq) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCameraReq.ProtoReflect.Descriptor instead.
func (*DeleteCameraReq) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteCameraReq) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

type DeleteCameraRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Camera *Camera `protobuf:"bytes,1,opt,name=camera,proto3" json:"camera,omitempty"`
}

func (x *DeleteCameraRes) Reset() {
	*x = DeleteCameraRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCameraRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCameraRes) ProtoMessage() {}

func (x *DeleteCameraRes) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCameraRes.ProtoReflect.Descriptor instead.
func (*DeleteCameraRes) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteCameraRes) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

type Processo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Processo) Reset() {
	*x = Processo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Processo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Processo) ProtoMessage() {}

func (x *Processo) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Processo.ProtoReflect.Descriptor instead.
func (*Processo) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{24}
}

type CreateProcessoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServidorGravacaoId string `protobuf:"bytes,1,opt,name=servidor_gravacao_id,json=servidorGravacaoId,proto3" json:"servidor_gravacao_id,omitempty"`
	CameraId           string `protobuf:"bytes,2,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	Processador        int32  `protobuf:"varint,3,opt,name=processador,proto3" json:"processador,omitempty"`
	Adaptador          int32  `protobuf:"varint,4,opt,name=adaptador,proto3" json:"adaptador,omitempty"`
	Execucao           bool   `protobuf:"varint,5,opt,name=execucao,proto3" json:"execucao,omitempty"`
}

func (x *CreateProcessoReq) Reset() {
	*x = CreateProcessoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateProcessoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProcessoReq) ProtoMessage() {}

func (x *CreateProcessoReq) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProcessoReq.ProtoReflect.Descriptor instead.
func (*CreateProcessoReq) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{25}
}

func (x *CreateProcessoReq) GetServidorGravacaoId() string {
	if x != nil {
		return x.ServidorGravacaoId
	}
	return ""
}

func (x *CreateProcessoReq) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *CreateProcessoReq) GetProcessador() int32 {
	if x != nil {
		return x.Processador
	}
	return 0
}

func (x *CreateProcessoReq) GetAdaptador() int32 {
	if x != nil {
		return x.Adaptador
	}
	return 0
}

func (x *CreateProcessoReq) GetExecucao() bool {
	if x != nil {
		return x.Execucao
	}
	return false
}

type CreateProcessoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessoId string `protobuf:"bytes,1,opt,name=processo_id,json=processoId,proto3" json:"processo_id,omitempty"`
}

func (x *CreateProcessoRes) Reset() {
	*x = CreateProcessoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateProcessoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProcessoRes) ProtoMessage() {}

func (x *CreateProcessoRes) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProcessoRes.ProtoReflect.Descriptor instead.
func (*CreateProcessoRes) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{26}
}

func (x *CreateProcessoRes) GetProcessoId() string {
	if x != nil {
		return x.ProcessoId
	}
	return ""
}

type ReadProcessoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadProcessoReq) Reset() {
	*x = ReadProcessoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadProcessoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadProcessoReq) ProtoMessage() {}

func (x *ReadProcessoReq) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadProcessoReq.ProtoReflect.Descriptor instead.
func (*ReadProcessoReq) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{27}
}

type ReadProcessoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadProcessoRes) Reset() {
	*x = ReadProcessoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadProcessoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadProcessoRes) ProtoMessage() {}

func (x *ReadProcessoRes) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadProcessoRes.ProtoReflect.Descriptor instead.
func (*ReadProcessoRes) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{28}
}

type UpdateProcessoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateProcessoReq) Reset() {
	*x = UpdateProcessoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProcessoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProcessoReq) ProtoMessage() {}

func (x *UpdateProcessoReq) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProcessoReq.ProtoReflect.Descriptor instead.
func (*UpdateProcessoReq) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{29}
}

type UpdateProcessoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateProcessoRes) Reset() {
	*x = UpdateProcessoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProcessoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProcessoRes) ProtoMessage() {}

func (x *UpdateProcessoRes) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProcessoRes.ProtoReflect.Descriptor instead.
func (*UpdateProcessoRes) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{30}
}

type DeleteProcessoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProcessoId string `protobuf:"bytes,1,opt,name=processo_id,json=processoId,proto3" json:"processo_id,omitempty"`
}

func (x *DeleteProcessoReq) Reset() {
	*x = DeleteProcessoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProcessoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProcessoReq) ProtoMessage() {}

func (x *DeleteProcessoReq) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProcessoReq.ProtoReflect.Descriptor instead.
func (*DeleteProcessoReq) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteProcessoReq) GetProcessoId() string {
	if x != nil {
		return x.ProcessoId
	}
	return ""
}

type DeleteProcessoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteProcessoRes) Reset() {
	*x = DeleteProcessoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gerencia_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProcessoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProcessoRes) ProtoMessage() {}

func (x *DeleteProcessoRes) ProtoReflect() protoreflect.Message {
	mi := &file_gerencia_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProcessoRes.ProtoReflect.Descriptor instead.
func (*DeleteProcessoRes) Descriptor() ([]byte, []int) {
	return file_gerencia_proto_rawDescGZIP(), []int{32}
}

var File_gerencia_proto protoreflect.FileDescriptor

var file_gerencia_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x08, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x63,
	0x61, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x63,
	0x61, 0x49, 0x64, 0x22, 0x0a, 0x0a, 0x08, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x22,
	0x24, 0x0a, 0x0a, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x65, 0x72, 0x73, 0x61, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x76,
	0x65, 0x72, 0x73, 0x61, 0x6f, 0x22, 0x0c, 0x0a, 0x0a, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x22, 0x83, 0x02, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72,
	0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x12, 0x30, 0x0a, 0x14, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x64, 0x6f, 0x72, 0x5f, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72,
	0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x65, 0x63, 0x6f, 0x5f, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x65, 0x63, 0x6f, 0x49, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x6f, 0x72, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x6f, 0x72, 0x74,
	0x61, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x09, 0x63, 0x72, 0x69, 0x61, 0x64, 0x6f, 0x5f,
	0x65, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x63, 0x72, 0x69, 0x61, 0x64, 0x6f, 0x45, 0x6d, 0x12, 0x39,
	0x0a, 0x0a, 0x65, 0x64, 0x69, 0x74, 0x61, 0x64, 0x6f, 0x5f, 0x65, 0x6d, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x65, 0x64, 0x69, 0x74, 0x61, 0x64, 0x6f, 0x45, 0x6d, 0x22, 0x64, 0x0a, 0x19, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61,
	0x63, 0x61, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x47, 0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64,
	0x6f, 0x72, 0x5f, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x10, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x22,
	0x64, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f,
	0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x47, 0x0a, 0x11,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x5f, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x69, 0x61, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61,
	0x63, 0x61, 0x6f, 0x52, 0x10, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61,
	0x76, 0x61, 0x63, 0x61, 0x6f, 0x22, 0x62, 0x0a, 0x17, 0x52, 0x65, 0x61, 0x64, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x65, 0x71,
	0x12, 0x47, 0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x5f, 0x67, 0x72, 0x61,
	0x76, 0x61, 0x63, 0x61, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47,
	0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x10, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f,
	0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x22, 0x62, 0x0a, 0x17, 0x52, 0x65, 0x61,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61,
	0x6f, 0x52, 0x65, 0x73, 0x12, 0x47, 0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72,
	0x5f, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x10, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x22, 0x64, 0x0a,
	0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47,
	0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x47, 0x0a, 0x11, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x5f, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61,
	0x6f, 0x52, 0x10, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61,
	0x63, 0x61, 0x6f, 0x22, 0x64, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x65, 0x73,
	0x12, 0x47, 0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x5f, 0x67, 0x72, 0x61,
	0x76, 0x61, 0x63, 0x61, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47,
	0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x10, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f,
	0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x22, 0x64, 0x0a, 0x19, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61,
	0x63, 0x61, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x47, 0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64,
	0x6f, 0x72, 0x5f, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x10, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x22,
	0x64, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f,
	0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x47, 0x0a, 0x11,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x5f, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x69, 0x61, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61,
	0x63, 0x61, 0x6f, 0x52, 0x10, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61,
	0x76, 0x61, 0x63, 0x61, 0x6f, 0x22, 0xdc, 0x02, 0x0a, 0x06, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x65, 0x63, 0x6f, 0x5f, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x65, 0x63, 0x6f, 0x49, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x6f, 0x72, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x6f, 0x72,
	0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x6e, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x63, 0x61, 0x6e, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x75, 0x61,
	0x72, 0x69, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x75, 0x61, 0x72,
	0x69, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x6e, 0x68, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x65, 0x6e, 0x68, 0x61, 0x12, 0x26, 0x0a, 0x0e, 0x67, 0x65, 0x6f, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x63, 0x61, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x67, 0x65, 0x6f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x63, 0x61, 0x6f,
	0x12, 0x37, 0x0a, 0x09, 0x63, 0x72, 0x69, 0x61, 0x64, 0x6f, 0x5f, 0x65, 0x6d, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x08, 0x63, 0x72, 0x69, 0x61, 0x64, 0x6f, 0x45, 0x6d, 0x12, 0x39, 0x0a, 0x0a, 0x65, 0x64, 0x69,
	0x74, 0x61, 0x64, 0x6f, 0x5f, 0x65, 0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x65, 0x64, 0x69, 0x74, 0x61,
	0x64, 0x6f, 0x45, 0x6d, 0x22, 0x3b, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61,
	0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x71, 0x12, 0x28, 0x0a, 0x06, 0x63, 0x61, 0x6d, 0x65, 0x72,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x69, 0x61, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x06, 0x63, 0x61, 0x6d, 0x65, 0x72,
	0x61, 0x22, 0x3b, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x6d, 0x65, 0x72,
	0x61, 0x52, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e,
	0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x06, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x22, 0x39,
	0x0a, 0x0d, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x71, 0x12,
	0x28, 0x0a, 0x06, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72,
	0x61, 0x52, 0x06, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x22, 0x39, 0x0a, 0x0d, 0x52, 0x65, 0x61,
	0x64, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x63, 0x61,
	0x6d, 0x65, 0x72, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x06, 0x63, 0x61,
	0x6d, 0x65, 0x72, 0x61, 0x22, 0x3a, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x6d, 0x65,
	0x72, 0x61, 0x73, 0x52, 0x65, 0x71, 0x12, 0x28, 0x0a, 0x06, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69,
	0x61, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x06, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61,
	0x22, 0x3c, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x73, 0x52,
	0x65, 0x73, 0x12, 0x2a, 0x0a, 0x07, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x43,
	0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x07, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x73, 0x22, 0x3b,
	0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65,
	0x71, 0x12, 0x28, 0x0a, 0x06, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x43, 0x61, 0x6d,
	0x65, 0x72, 0x61, 0x52, 0x06, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x22, 0x3b, 0x0a, 0x0f, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x73, 0x12, 0x28,
	0x0a, 0x06, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61,
	0x52, 0x06, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x22, 0x3b, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x71, 0x12, 0x28, 0x0a, 0x06, 0x63,
	0x61, 0x6d, 0x65, 0x72, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x06, 0x63,
	0x61, 0x6d, 0x65, 0x72, 0x61, 0x22, 0x3b, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x63, 0x61, 0x6d, 0x65,
	0x72, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x69, 0x61, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x06, 0x63, 0x61, 0x6d, 0x65,
	0x72, 0x61, 0x22, 0x0a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x22, 0xbe,
	0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x52, 0x65, 0x71, 0x12, 0x30, 0x0a, 0x14, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72,
	0x5f, 0x67, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x12, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76,
	0x61, 0x63, 0x61, 0x6f, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6d, 0x65, 0x72,
	0x61, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x61, 0x64,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x64, 0x61, 0x70, 0x74, 0x61, 0x64,
	0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x64, 0x61, 0x70, 0x74, 0x61,
	0x64, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x65, 0x63, 0x75, 0x63, 0x61, 0x6f, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x65, 0x78, 0x65, 0x63, 0x75, 0x63, 0x61, 0x6f, 0x22,
	0x34, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x52, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x49, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x71, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x71,
	0x22, 0x13, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x34, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x49, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x73,
	0x32, 0x99, 0x09, 0x0a, 0x08, 0x47, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x12, 0x31, 0x0a,
	0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x12, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69,
	0x61, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x67, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x37, 0x0a, 0x07, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x67, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x14, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x4d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x64, 0x0a, 0x16, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61,
	0x63, 0x61, 0x6f, 0x12, 0x23, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61,
	0x76, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x69, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64,
	0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x5e, 0x0a, 0x14, 0x52, 0x65, 0x61, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47,
	0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x12, 0x21, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x69, 0x61, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47,
	0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x67, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64,
	0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x64, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f,
	0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x12, 0x23, 0x2e, 0x67, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x69, 0x61, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x23,
	0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f,
	0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x64, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x12,
	0x23, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72, 0x61, 0x76, 0x61, 0x63, 0x61,
	0x6f, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x47, 0x72,
	0x61, 0x76, 0x61, 0x63, 0x61, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0c, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x12, 0x19, 0x2e, 0x67, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x6d,
	0x65, 0x72, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69,
	0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0a, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x6d, 0x65, 0x72,
	0x61, 0x12, 0x17, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x52, 0x65, 0x61,
	0x64, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x67, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61,
	0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x6d,
	0x65, 0x72, 0x61, 0x73, 0x12, 0x18, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x18,
	0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x61,
	0x6d, 0x65, 0x72, 0x61, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0c, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x12, 0x19, 0x2e, 0x67, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x6d, 0x65,
	0x72, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x12, 0x46, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x6d, 0x65,
	0x72, 0x61, 0x12, 0x19, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e,
	0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x12, 0x1b, 0x2e, 0x67,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x67, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x69, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x12, 0x19, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x69, 0x61, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x4c, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x12, 0x1b, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x71, 0x1a,
	0x1b, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x4c,
	0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x12, 0x1b, 0x2e, 0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e,
	0x67, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x69, 0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e,
	0x2e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gerencia_proto_rawDescOnce sync.Once
	file_gerencia_proto_rawDescData = file_gerencia_proto_rawDesc
)

func file_gerencia_proto_rawDescGZIP() []byte {
	file_gerencia_proto_rawDescOnce.Do(func() {
		file_gerencia_proto_rawDescData = protoimpl.X.CompressGZIP(file_gerencia_proto_rawDescData)
	})
	return file_gerencia_proto_rawDescData
}

var file_gerencia_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_gerencia_proto_goTypes = []interface{}{
	(*MatchReq)(nil),                  // 0: gerencia.MatchReq
	(*MatchRes)(nil),                  // 1: gerencia.MatchRes
	(*MigrateReq)(nil),                // 2: gerencia.MigrateReq
	(*MigrateRes)(nil),                // 3: gerencia.MigrateRes
	(*ServidorGravacao)(nil),          // 4: gerencia.ServidorGravacao
	(*CreateServidorGravacaoReq)(nil), // 5: gerencia.CreateServidorGravacaoReq
	(*CreateServidorGravacaoRes)(nil), // 6: gerencia.CreateServidorGravacaoRes
	(*ReadServidorGravacaoReq)(nil),   // 7: gerencia.ReadServidorGravacaoReq
	(*ReadServidorGravacaoRes)(nil),   // 8: gerencia.ReadServidorGravacaoRes
	(*UpdateServidorGravacaoReq)(nil), // 9: gerencia.UpdateServidorGravacaoReq
	(*UpdateServidorGravacaoRes)(nil), // 10: gerencia.UpdateServidorGravacaoRes
	(*DeleteServidorGravacaoReq)(nil), // 11: gerencia.DeleteServidorGravacaoReq
	(*DeleteServidorGravacaoRes)(nil), // 12: gerencia.DeleteServidorGravacaoRes
	(*Camera)(nil),                    // 13: gerencia.Camera
	(*CreateCameraReq)(nil),           // 14: gerencia.CreateCameraReq
	(*CreateCameraRes)(nil),           // 15: gerencia.CreateCameraRes
	(*ReadCameraReq)(nil),             // 16: gerencia.ReadCameraReq
	(*ReadCameraRes)(nil),             // 17: gerencia.ReadCameraRes
	(*ReadCamerasReq)(nil),            // 18: gerencia.ReadCamerasReq
	(*ReadCamerasRes)(nil),            // 19: gerencia.ReadCamerasRes
	(*UpdateCameraReq)(nil),           // 20: gerencia.UpdateCameraReq
	(*UpdateCameraRes)(nil),           // 21: gerencia.UpdateCameraRes
	(*DeleteCameraReq)(nil),           // 22: gerencia.DeleteCameraReq
	(*DeleteCameraRes)(nil),           // 23: gerencia.DeleteCameraRes
	(*Processo)(nil),                  // 24: gerencia.Processo
	(*CreateProcessoReq)(nil),         // 25: gerencia.CreateProcessoReq
	(*CreateProcessoRes)(nil),         // 26: gerencia.CreateProcessoRes
	(*ReadProcessoReq)(nil),           // 27: gerencia.ReadProcessoReq
	(*ReadProcessoRes)(nil),           // 28: gerencia.ReadProcessoRes
	(*UpdateProcessoReq)(nil),         // 29: gerencia.UpdateProcessoReq
	(*UpdateProcessoRes)(nil),         // 30: gerencia.UpdateProcessoRes
	(*DeleteProcessoReq)(nil),         // 31: gerencia.DeleteProcessoReq
	(*DeleteProcessoRes)(nil),         // 32: gerencia.DeleteProcessoRes
	(*timestamppb.Timestamp)(nil),     // 33: google.protobuf.Timestamp
}
var file_gerencia_proto_depIdxs = []int32{
	33, // 0: gerencia.ServidorGravacao.criado_em:type_name -> google.protobuf.Timestamp
	33, // 1: gerencia.ServidorGravacao.editado_em:type_name -> google.protobuf.Timestamp
	4,  // 2: gerencia.CreateServidorGravacaoReq.servidor_gravacao:type_name -> gerencia.ServidorGravacao
	4,  // 3: gerencia.CreateServidorGravacaoRes.servidor_gravacao:type_name -> gerencia.ServidorGravacao
	4,  // 4: gerencia.ReadServidorGravacaoReq.servidor_gravacao:type_name -> gerencia.ServidorGravacao
	4,  // 5: gerencia.ReadServidorGravacaoRes.servidor_gravacao:type_name -> gerencia.ServidorGravacao
	4,  // 6: gerencia.UpdateServidorGravacaoReq.servidor_gravacao:type_name -> gerencia.ServidorGravacao
	4,  // 7: gerencia.UpdateServidorGravacaoRes.servidor_gravacao:type_name -> gerencia.ServidorGravacao
	4,  // 8: gerencia.DeleteServidorGravacaoReq.servidor_gravacao:type_name -> gerencia.ServidorGravacao
	4,  // 9: gerencia.DeleteServidorGravacaoRes.servidor_gravacao:type_name -> gerencia.ServidorGravacao
	33, // 10: gerencia.Camera.criado_em:type_name -> google.protobuf.Timestamp
	33, // 11: gerencia.Camera.editado_em:type_name -> google.protobuf.Timestamp
	13, // 12: gerencia.CreateCameraReq.camera:type_name -> gerencia.Camera
	13, // 13: gerencia.CreateCameraRes.camera:type_name -> gerencia.Camera
	13, // 14: gerencia.ReadCameraReq.camera:type_name -> gerencia.Camera
	13, // 15: gerencia.ReadCameraRes.camera:type_name -> gerencia.Camera
	13, // 16: gerencia.ReadCamerasReq.camera:type_name -> gerencia.Camera
	13, // 17: gerencia.ReadCamerasRes.cameras:type_name -> gerencia.Camera
	13, // 18: gerencia.UpdateCameraReq.camera:type_name -> gerencia.Camera
	13, // 19: gerencia.UpdateCameraRes.camera:type_name -> gerencia.Camera
	13, // 20: gerencia.DeleteCameraReq.camera:type_name -> gerencia.Camera
	13, // 21: gerencia.DeleteCameraRes.camera:type_name -> gerencia.Camera
	0,  // 22: gerencia.Gerencia.Match:input_type -> gerencia.MatchReq
	2,  // 23: gerencia.Gerencia.Migrate:input_type -> gerencia.MigrateReq
	5,  // 24: gerencia.Gerencia.CreateServidorGravacao:input_type -> gerencia.CreateServidorGravacaoReq
	7,  // 25: gerencia.Gerencia.ReadServidorGravacao:input_type -> gerencia.ReadServidorGravacaoReq
	9,  // 26: gerencia.Gerencia.UpdateServidorGravacao:input_type -> gerencia.UpdateServidorGravacaoReq
	11, // 27: gerencia.Gerencia.DeleteServidorGravacao:input_type -> gerencia.DeleteServidorGravacaoReq
	14, // 28: gerencia.Gerencia.CreateCamera:input_type -> gerencia.CreateCameraReq
	16, // 29: gerencia.Gerencia.ReadCamera:input_type -> gerencia.ReadCameraReq
	18, // 30: gerencia.Gerencia.ReadCameras:input_type -> gerencia.ReadCamerasReq
	20, // 31: gerencia.Gerencia.UpdateCamera:input_type -> gerencia.UpdateCameraReq
	22, // 32: gerencia.Gerencia.DeleteCamera:input_type -> gerencia.DeleteCameraReq
	25, // 33: gerencia.Gerencia.CreateProcesso:input_type -> gerencia.CreateProcessoReq
	27, // 34: gerencia.Gerencia.ReadProcesso:input_type -> gerencia.ReadProcessoReq
	29, // 35: gerencia.Gerencia.UpdateProcesso:input_type -> gerencia.UpdateProcessoReq
	31, // 36: gerencia.Gerencia.DeleteProcesso:input_type -> gerencia.DeleteProcessoReq
	1,  // 37: gerencia.Gerencia.Match:output_type -> gerencia.MatchRes
	3,  // 38: gerencia.Gerencia.Migrate:output_type -> gerencia.MigrateRes
	6,  // 39: gerencia.Gerencia.CreateServidorGravacao:output_type -> gerencia.CreateServidorGravacaoRes
	8,  // 40: gerencia.Gerencia.ReadServidorGravacao:output_type -> gerencia.ReadServidorGravacaoRes
	10, // 41: gerencia.Gerencia.UpdateServidorGravacao:output_type -> gerencia.UpdateServidorGravacaoRes
	12, // 42: gerencia.Gerencia.DeleteServidorGravacao:output_type -> gerencia.DeleteServidorGravacaoRes
	15, // 43: gerencia.Gerencia.CreateCamera:output_type -> gerencia.CreateCameraRes
	17, // 44: gerencia.Gerencia.ReadCamera:output_type -> gerencia.ReadCameraRes
	19, // 45: gerencia.Gerencia.ReadCameras:output_type -> gerencia.ReadCamerasRes
	21, // 46: gerencia.Gerencia.UpdateCamera:output_type -> gerencia.UpdateCameraRes
	23, // 47: gerencia.Gerencia.DeleteCamera:output_type -> gerencia.DeleteCameraRes
	26, // 48: gerencia.Gerencia.CreateProcesso:output_type -> gerencia.CreateProcessoRes
	28, // 49: gerencia.Gerencia.ReadProcesso:output_type -> gerencia.ReadProcessoRes
	30, // 50: gerencia.Gerencia.UpdateProcesso:output_type -> gerencia.UpdateProcessoRes
	32, // 51: gerencia.Gerencia.DeleteProcesso:output_type -> gerencia.DeleteProcessoRes
	37, // [37:52] is the sub-list for method output_type
	22, // [22:37] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_gerencia_proto_init() }
func file_gerencia_proto_init() {
	if File_gerencia_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gerencia_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServidorGravacao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateServidorGravacaoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateServidorGravacaoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadServidorGravacaoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadServidorGravacaoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateServidorGravacaoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateServidorGravacaoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteServidorGravacaoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteServidorGravacaoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Camera); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCameraReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCameraRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadCameraReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadCameraRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadCamerasReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadCamerasRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCameraReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCameraRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCameraReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCameraRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Processo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateProcessoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateProcessoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadProcessoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadProcessoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProcessoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProcessoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteProcessoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gerencia_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteProcessoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gerencia_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gerencia_proto_goTypes,
		DependencyIndexes: file_gerencia_proto_depIdxs,
		MessageInfos:      file_gerencia_proto_msgTypes,
	}.Build()
	File_gerencia_proto = out.File
	file_gerencia_proto_rawDesc = nil
	file_gerencia_proto_goTypes = nil
	file_gerencia_proto_depIdxs = nil
}
