// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GerenciaClient is the client API for Gerencia service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GerenciaClient interface {
	IniciarProcesso(ctx context.Context, in *Params, opts ...grpc.CallOption) (*StatusIniciar, error)
	AlterarProcesso(ctx context.Context, in *Params, opts ...grpc.CallOption) (*StatusAlterar, error)
	PararProcesso(ctx context.Context, in *Camera, opts ...grpc.CallOption) (*StatusParar, error)
	RemoverProcesso(ctx context.Context, in *Camera, opts ...grpc.CallOption) (*StatusRemover, error)
	StatusArmazenamentoGravacao(ctx context.Context, in *ArmazenamentoParams, opts ...grpc.CallOption) (*StatusArmazenamento, error)
}

type gerenciaClient struct {
	cc grpc.ClientConnInterface
}

func NewGerenciaClient(cc grpc.ClientConnInterface) GerenciaClient {
	return &gerenciaClient{cc}
}

func (c *gerenciaClient) IniciarProcesso(ctx context.Context, in *Params, opts ...grpc.CallOption) (*StatusIniciar, error) {
	out := new(StatusIniciar)
	err := c.cc.Invoke(ctx, "/pb.Gerencia/iniciarProcesso", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gerenciaClient) AlterarProcesso(ctx context.Context, in *Params, opts ...grpc.CallOption) (*StatusAlterar, error) {
	out := new(StatusAlterar)
	err := c.cc.Invoke(ctx, "/pb.Gerencia/alterarProcesso", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gerenciaClient) PararProcesso(ctx context.Context, in *Camera, opts ...grpc.CallOption) (*StatusParar, error) {
	out := new(StatusParar)
	err := c.cc.Invoke(ctx, "/pb.Gerencia/pararProcesso", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gerenciaClient) RemoverProcesso(ctx context.Context, in *Camera, opts ...grpc.CallOption) (*StatusRemover, error) {
	out := new(StatusRemover)
	err := c.cc.Invoke(ctx, "/pb.Gerencia/removerProcesso", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gerenciaClient) StatusArmazenamentoGravacao(ctx context.Context, in *ArmazenamentoParams, opts ...grpc.CallOption) (*StatusArmazenamento, error) {
	out := new(StatusArmazenamento)
	err := c.cc.Invoke(ctx, "/pb.Gerencia/statusArmazenamentoGravacao", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GerenciaServer is the server API for Gerencia service.
// All implementations must embed UnimplementedGerenciaServer
// for forward compatibility
type GerenciaServer interface {
	IniciarProcesso(context.Context, *Params) (*StatusIniciar, error)
	AlterarProcesso(context.Context, *Params) (*StatusAlterar, error)
	PararProcesso(context.Context, *Camera) (*StatusParar, error)
	RemoverProcesso(context.Context, *Camera) (*StatusRemover, error)
	StatusArmazenamentoGravacao(context.Context, *ArmazenamentoParams) (*StatusArmazenamento, error)
	mustEmbedUnimplementedGerenciaServer()
}

// UnimplementedGerenciaServer must be embedded to have forward compatible implementations.
type UnimplementedGerenciaServer struct {
}

func (UnimplementedGerenciaServer) IniciarProcesso(context.Context, *Params) (*StatusIniciar, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IniciarProcesso not implemented")
}
func (UnimplementedGerenciaServer) AlterarProcesso(context.Context, *Params) (*StatusAlterar, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlterarProcesso not implemented")
}
func (UnimplementedGerenciaServer) PararProcesso(context.Context, *Camera) (*StatusParar, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PararProcesso not implemented")
}
func (UnimplementedGerenciaServer) RemoverProcesso(context.Context, *Camera) (*StatusRemover, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoverProcesso not implemented")
}
func (UnimplementedGerenciaServer) StatusArmazenamentoGravacao(context.Context, *ArmazenamentoParams) (*StatusArmazenamento, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatusArmazenamentoGravacao not implemented")
}
func (UnimplementedGerenciaServer) mustEmbedUnimplementedGerenciaServer() {}

// UnsafeGerenciaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GerenciaServer will
// result in compilation errors.
type UnsafeGerenciaServer interface {
	mustEmbedUnimplementedGerenciaServer()
}

func RegisterGerenciaServer(s grpc.ServiceRegistrar, srv GerenciaServer) {
	s.RegisterService(&Gerencia_ServiceDesc, srv)
}

func _Gerencia_IniciarProcesso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Params)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GerenciaServer).IniciarProcesso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Gerencia/iniciarProcesso",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GerenciaServer).IniciarProcesso(ctx, req.(*Params))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gerencia_AlterarProcesso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Params)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GerenciaServer).AlterarProcesso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Gerencia/alterarProcesso",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GerenciaServer).AlterarProcesso(ctx, req.(*Params))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gerencia_PararProcesso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Camera)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GerenciaServer).PararProcesso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Gerencia/pararProcesso",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GerenciaServer).PararProcesso(ctx, req.(*Camera))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gerencia_RemoverProcesso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Camera)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GerenciaServer).RemoverProcesso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Gerencia/removerProcesso",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GerenciaServer).RemoverProcesso(ctx, req.(*Camera))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gerencia_StatusArmazenamentoGravacao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArmazenamentoParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GerenciaServer).StatusArmazenamentoGravacao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Gerencia/statusArmazenamentoGravacao",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GerenciaServer).StatusArmazenamentoGravacao(ctx, req.(*ArmazenamentoParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Gerencia_ServiceDesc is the grpc.ServiceDesc for Gerencia service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gerencia_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Gerencia",
	HandlerType: (*GerenciaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "iniciarProcesso",
			Handler:    _Gerencia_IniciarProcesso_Handler,
		},
		{
			MethodName: "alterarProcesso",
			Handler:    _Gerencia_AlterarProcesso_Handler,
		},
		{
			MethodName: "pararProcesso",
			Handler:    _Gerencia_PararProcesso_Handler,
		},
		{
			MethodName: "removerProcesso",
			Handler:    _Gerencia_RemoverProcesso_Handler,
		},
		{
			MethodName: "statusArmazenamentoGravacao",
			Handler:    _Gerencia_StatusArmazenamentoGravacao_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gerencia.proto",
}
