## Build
FROM golang:1.16-buster AS build

WORKDIR /app

COPY ./go.mod go.sum ./
RUN go mod download

COPY ./cmd ./cmd
COPY ./internal ./internal

RUN go build -o ./build/gerencia ./cmd/gerencia

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /app

COPY --from=build /app/build/gerencia ./gerencia

USER nonroot:nonroot

ENTRYPOINT ["/app/gerencia"]